// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe5pL1Gp_VYIipZrgbbYGA4kyd-8q7vfQ',
    appId: '1:760619240003:web:4f8d8551e9b4379cc7a2f6',
    messagingSenderId: '760619240003',
    projectId: 't-store-by-awais',
    authDomain: 't-store-by-awais.firebaseapp.com',
    storageBucket: 't-store-by-awais.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChT_buIzE8llFpWKJTVvFjY-tpho3qtL4',
    appId: '1:760619240003:android:ff25c9e63a8bf0cfc7a2f6',
    messagingSenderId: '760619240003',
    projectId: 't-store-by-awais',
    storageBucket: 't-store-by-awais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzvkR9MN2SVnTs98FDvQwvRKPmwKT-qBU',
    appId: '1:760619240003:ios:d1da3e0182d93f84c7a2f6',
    messagingSenderId: '760619240003',
    projectId: 't-store-by-awais',
    storageBucket: 't-store-by-awais.firebasestorage.app',
    iosBundleId: 'com.example.tStore',
  );
}
